routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('events', 'WEB\EventController');

Route::resource('activities', 'WEB\ActivityController')->except([
    'create'
]);

Route::group(['middleware' => ['admin']], function () {

    Route::get('/events/organizers/search/{event_id}', 'WEB\EventController@searchOrganizers')->name('organizers.search');

    Route::get('/events/organizers/{event_id}', 'WEB\EventController@createOrganizers')->name('organizers.create');

    Route::post('/events/organizers', 'WEB\EventController@storeOrganizers')->name('organizers.store');

});

Route::group(['middleware' => ['organizer']], function () {

    Route::get('/activities/create/{event_id}', 'WEB\ActivityController@create')->name('activities.create');

    Route::get('/activities/referees/search/{activity_id}', 'WEB\ActivityController@searchReferees')->name('referees.search');

    Route::get('/activities/referees/{activity_id}', 'WEB\ActivityController@createReferees')->name('referees.create');

    Route::post('/activities/referees', 'WEB\ActivityController@storeReferees')->name('referees.store');

});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{

	protected $fillable = [
        'description', 'start_date', 'end_date',
    ];


    public function activities()
    {
        return $this->hasMany('App\Models\Activity');
    }

    public function organizers()
    {
        return $this->belongsToMany('App\Models\User', 'event_organizer');
    }

}

app/Http/Controllers/API/EventController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\Events as EventsResource;
use App\Models\User;
use App\Models\Event;

class EventController extends Controller
{
    public function index(){
        return response()->json([
            'status'=>true,
            'message'=>'Todos los eventos registrados',
            'data'=> EventsResource::collection(Event::all())
        ],200);
    }

    public function show(Event $event){
        return response()->json([
            'status' => true,
            'message' => 'Evento encontrado',
            'data' => new EventsResource($event)
        ],200);
    }
}

app/Http/Controllers/WEB/EventController.php
<?php

namespace App\Http\Controllers\WEB;

use Illuminate\Http\Request;
use App\Models\Event;
use App\Models\User;
use App\Models\Role;
use App\Http\Controllers\Controller;
use Session;

class EventController extends Controller
{
    public function index()
    {
        $events = Event::all();

        return view('events.index')->with('events', $events);
    }

    public function show($event)
    {
        $event = Event::find($event);

        return view('events.show')->with('event', $event);
    }

    public function create()
    {
        return view('events.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'description' => 'required|unique:events|max:255',
            'start_date' => 'required|date',
            'end_date' => 'required|date|after_or_equal:start_date',
        ]);

        $event = Event::create($validatedData);

        $request->session()->flash('status', 'Evento creado exitosamente');

        return view('events.show')->with('event', $event);
    }

    
    public function searchOrganizers($event_id)
    {
        $event = Event::findOrFail($event_id);

        return view('organizers.search')->with('event', $event);
    }

    public function createOrganizers(Request $request)
    {
        $users = User::where('name', 'like', '%'.$request->search.'%')
                      ->orWhere('email', 'like', '%'.$request->search.'%')
						 ->orWhere('phone', 'like', '%'.$request->search.'%')->get();
    
        $event = Event::find($request->event_id);
        
        $admins = Role::where('name', 'admin')->first()->users;
        
        $organizers = $event->organizers;
        
        $new_organizers = $users->diff($organizers->merge($admins))->take(10);
        
        if ($new_organizers->count() < 1) {
            $request->session()->flash('info', 'No se encontraron resultados de búsqueda. Por favor, intente con otro término');
            return back();
        }
        return view('organizers.create')->with(['users' => $new_organizers, 'event' => $event]);
    }

    public function storeOrganizers(Request $request)
    {
        $event = Event::findOrFail($request->event_id);

        $event->organizers()->attach($request->organizers);

        $request->session()->flash('status', 'Organizador(es) añadidos exitosamente');

        return redirect()->route('events.show', $event->id);
    }
}

resources/views/events/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  @if ($errors->any())
  <div class="alert alert-danger" role="alert">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
  @endif
</div>
<div class="container d-flex justify-content-center">
  <div class="card border-primary col-lg-6">
    <div class="card-header">Crear evento</div>
    <div class="card-body">
      <h4 class="card-title">Crear un evento</h4>
      <form method="POST" action="{{ route('events.store') }}">
        @csrf
        <div class="form-group">
          <label for="inputDescription">Descripción</label>
          <input type="text" class="form-control" id="inputDescription" name="description" aria-describedby="descriptionHelp" placeholder="Ingrese la descripción" required>
          <small id="descriptionHelp" class="form-text text-muted">Ingrese la descripción del evento a crear</small>
        </div>
        <div class="form-group">
          <label for="inputStartDate">Fecha de inicio</label>
          <input type="datetime-local" class="form-control" id="inputStartDate" name="start_date" aria-describedby="start_dateHelp" placeholder="DD/MM/AAAA" required>
          <small id="start_dateHelp" class="form-text text-muted">Ingrese la fecha de inicio del evento a crear</small>
        </div>
        <div class="form-group">
          <label for="inputEndDate">Fecha de fin</label>
          <input type="datetime-local" class="form-control" id="inputEndDate" name="end_date" aria-describedby="end_dateHelp" placeholder="DD/MM/AAAA" required>
          <small id="end_dateHelp" class="form-text text-muted">Ingrese la fecha de fin del evento a crear</small>
        </div>
        <button type="submit" class="btn btn-primary">Crear evento</button>
      </form>
    </div>
  </div>
</div>


@section('pagescript')
<script src="{{asset('/js/events.js')}}"></script>
@stop

@endsection

resources/views/events/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif

  <div class="mb-3">
    <h1 class="d-inline"> Eventos </h1> 
    @if(Auth::user() && Auth::user()->roles()->where('name','admin')->first()) 
    <a class="btn btn-success mb-3 float-right" href="{{ route('events.create') }}">Crear evento</a>
    @endif
  </div>    
  <div class="bs-component">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Descripción</th>
          <th scope="col">Fecha Inicio</th>
          <th scope="col">Fecha Fin</th>
        </tr>
      </thead>
      <tbody>
        @foreach($events as $event)
        <tr class="clickable-row" data-href="{{ route('events.show', $event->id) }}">
         <td>
          {{$event->description}}
        </td>
        <td>

         {{Carbon\Carbon::parse($event->start_date)->format('d/m/Y')}}
       </td>
       <td>
         {{Carbon\Carbon::parse($event->end_date)->format('d/m/Y')}}
       </td>
     </tr>

     @endforeach
   </tbody>
 </table>
</div>
</div>


@section('pagescript')
<script src="{{asset('/js/events.js')}}"></script>
@stop

@endsection

resources/views/events/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <div class="mb-3">
    <h3 class="d-inline">
      {{$event->description}}
    </h3>
    @if(Auth::user() && Auth::user()->roles()->where('name','admin')->first()) 
     <a class="btn btn-info mb-3 float-right mr-2" href="{{ route('organizers.search', $event->id) }}">Añadir organizadores</a>
     <a class="btn btn-success mb-3 float-right mr-2" href="{{ route('activities.create', $event->id) }}">Crear actividad</a>
    @endif
  </div>
  <div class="bs-component">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Descripción</th>
          <th scope="col">Tipo</th>
          <th scope="col">Capacidad</th>
          <th scope="col">Espacio</th>
          <th scope="col">Temática</th>
          <th scope="col">Hora Inicio</th>
          <th scope="col">Hora Fin</th>

        </tr>
      </thead>
      <tbody>
        @foreach($event->activities as $activity)
        <tr class="clickable-row" data-href="{{ route('activities.show', $activity->id) }}">
         <td>
           {{ $activity->description }}
         </td>
         <td>
          {{ __($activity->type) }}
        </td>
        <td>
          {{ $activity->capacity }}
        </td>
        <td>
          {{ $activity->place->description }}
        </td>
        <td>
          {{ $activity->thematic->description }}
        </td>
        <td>
          {{ Carbon\Carbon::parse($activity->start_date)->format('d/m/Y h:m a') }}
        </td>
        <td>
          {{ Carbon\Carbon::parse($activity->end_date)->format('d/m/Y h:m a') }}
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@if($event->organizers->count() > 0)
<div class="mb-3">
  <h4 class="d-inline">
    Organizadores
  </h4>
</div>
<div class="bs-component">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">E-mail</th>
        <th scope="col">Telefono</th>

      </tr>
    </thead>
    <tbody>
      @foreach($event->organizers as $organizer)
      <tr>
       <td>
         {{ $organizer->name }}
       </td>
       <td>
        {{ $organizer->email }}
      </td>
      <td>
        {{ $organizer->phone }}
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
</div>
@endif
</div>


@section('pagescript')
<script src="{{asset('/js/events.js')}}"></script>
@stop

@endsection