routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('events', 'WEB\EventController');

Route::resource('activities', 'WEB\ActivityController')->except([
    'create'
]);

Route::group(['middleware' => ['admin']], function () {

    Route::get('/events/organizers/search/{event_id}', 'WEB\EventController@searchOrganizers')->name('organizers.search');

    Route::get('/events/organizers/{event_id}', 'WEB\EventController@createOrganizers')->name('organizers.create');

    Route::post('/events/organizers', 'WEB\EventController@storeOrganizers')->name('organizers.store');

});

Route::group(['middleware' => ['organizer']], function () {

    Route::get('/activities/create/{event_id}', 'WEB\ActivityController@create')->name('activities.create');

    Route::get('/activities/referees/search/{activity_id}', 'WEB\ActivityController@searchReferees')->name('referees.search');

    Route::get('/activities/referees/{activity_id}', 'WEB\ActivityController@createReferees')->name('referees.create');

    Route::post('/activities/referees', 'WEB\ActivityController@storeReferees')->name('referees.store');

});

app/Models/Activity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{

    protected $fillable = [
        'description', 'start_date', 'end_date','user_id', 'type', 'place_id','capacity','status','event_id','thematic_id',
    ];

    public function event()
    {
        return $this->belongsTo('App\Models\Event');
    }

    public function place()
    {
        return $this->belongsTo('App\Models\Place');
    }

    public function thematic()
    {
        return $this->belongsTo('App\Models\Thematic');
    }

    public function responsible()
    {
        return $this->belongsTo('App\Models\User','user_id');
    }

    public function necessities()
    {
        return $this->hasMany('App\Models\Necessity');
    }

    public function documents()
    {
        return $this->hasMany('App\Models\File');
    }

    public function evaluations()
    {
        return $this->belongsToMany('App\Models\User', 'evaluation_presentation');
    }

    public function referees()
    {
        return $this->belongsToMany('App\Models\User', 'presentation_referee');
    }
}

app/Http/Controllers/API/ActivityController.php
<?php

namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Http\Resources\Activities as ActivitiesResource;
use Illuminate\Http\Request;
use App\Models\Activity;
use App\Models\User;
use Auth;

class ActivityController extends Controller
{
    public function index () {
        return response()->json([
            'status' => true,
            'message' => 'Todas las actividades',
            'data' => ActivitiesResource::collection(Activity::all())
        ],200);
    }

    public function show(Activity $activity){
        return response()->json([
            'status' => true,
            'message' => 'Actividad encontrada',
            'data' => new ActivitiesResource($activity)
        ],200);
    }

    public function userAuth () {
        return response()->json([
            'status' => true,
            'message' => 'Actividades del usuario en sesion',
            'data' => ActivitiesResource::collection(Auth::user()->activities)
        ],200);
    }

    public function showUser (User $user) {
        return response()->json([
            'status' => true,
            'message' => 'Actividades del usuario buscado',
            'data' => ActivitiesResource::collection($user->activities)
        ],200);
    }

    public function referees (Activity $activity) {
        return response()->json([
            'status' => true,
            'message' => 'Referees de la actividad',
            'data' => $activity->referees
        ],200);
    }
}

app/Http/Controllers/WEB/ActivityController.php
<?php

namespace App\Http\Controllers\WEB;

use Illuminate\Http\Request;
use App\Models\Activity;
use App\Models\Event;
use App\Models\User;
use App\Models\Place;
use App\Models\Thematic;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Carbon\Carbon;
use Auth;

class ActivityController extends Controller
{
    public function show($activity_id)
    {
        $activity = Activity::findOrFail($activity_id);

        return view('activities.show')->with('activity', $activity);
    }

    public function create($event_id)
    {
        $event = Event::findOrFail($event_id);

        $users = User::orderBy('name')->get();

        $places = Place::all();

        $thematics = Thematic::all();

        return view('activities.create')->with([
            'event' => $event,
            'users' => $users,
            'places' => $places,
            'thematics' => $thematics
        ]);
    }

    public function store(Request $request)
    {
        $request->start_date = new Carbon($request->start_date);
        $request->end_date = new Carbon($request->end_date);

        $validatedData = $request->validate([
            'description' => 'required|max:255',
            'start_date' => 'required|date',
            'end_date' => 'required|date|after_or_equal:start_date',
            'user_id' => 'required|exists:users,id',
            'event_id' => 'required|exists:events,id',
            'type' => [
                'required',
                Rule::in(['Forum', 'Presentation', 'Conference']),
            ],
            'place_id' => 'required|exists:places,id',
            'capacity' => 'required|numeric',
            'status' => [
                'required',
                Rule::in([0]),
            ],
            'thematic_id' => 'required|exists:thematics,id',
        ]);

        $colliding_date =	Activity::where('event_id', $request->event_id)
                            ->where('place_id', $request->place_id)
                            ->whereBetween('start_date', [$request->start_date, $request->end_date])
                            ->whereBetween('end_date', [$request->start_date, $request->end_date])
                            ->get();

        if ($colliding_date->count() > 0) {
            $request->session()->flash('error', 'No se pudo crear la actividad. Ya existe una actividad en el horario y espacio indicados.');
            return back()->withInput();
        }
        $colliding_conference =	Activity::where('event_id', $request->event_id)
                                ->whereBetween('start_date', [$request->start_date, $request->end_date])
                                ->whereBetween('end_date', [$request->start_date, $request->end_date])
                                -where('type', 'Conference')
                                ->get();

        if ($colliding_conference->count() > 0) {
            $request->session()->flash('error', 'No se pudo crear la actividad. Existe una Conferencia en el horario indicado.');
            return back()->withInput();
        }

        $activity = Activity::create($validatedData);

        return view('activities.show')->with('activity', $activity);
    }

    public function searchReferees($activity_id)
    {
        $activity = Activity::findOrFail($activity_id);

        return view('referees.search')->with('activity', $activity);
    }
    
    public function createReferees(Request $request)
    {
        $users = User::where('name', 'like', '%'.$request->search.'%')
                      ->orWhere('email', 'like', '%'.$request->search.'%')
                         ->orWhere('phone', 'like', '%'.$request->search.'%')->get();
                         
        $activity = Activity::find($request->activity_id);
         
        $referees = $activity->referees;
        
        $new_referees = $users->diff($referees);

        $new_referees = $new_referees->where('id', '!=', Auth::user()->id);
    
        if ($new_referees->count() < 1) {
            $request->session()->flash('info', 'No se encontraron resultados de búsqueda. Por favor, intente con otro término');
            return back();
        }
        return view('referees.create')->with(['users' => $new_referees->take(10), 'activity' => $activity]);
    }
    
    public function storeReferees(Request $request)
    {
        $activity = Activity::findOrFail($request->activity_id);

        if ($activity->type !='Presentation') {
            return back();
        }

        $activity->referees()->attach($request->referees);

        $request->session()->flash('status', 'Árbitros añadidos exitosamente');

        return redirect()->route('activities.show', $activity->id);
    }
}

resources/views/activities/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
    @if (session('error'))
  <div class="alert alert-danger" role="alert">
    {{ session('error') }}
  </div>
  @endif
  @if ($errors->any())
  <div class="alert alert-danger" role="alert">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
  @endif
</div>
<div class="container d-flex justify-content-center">
  <div class="card border-primary col-lg-6">
    <div class="card-header">Crear actividad</div>
    <div class="card-body">
      <h4 class="card-title">Crear una actividad</h4>
      <form method="POST" action="{{ route('activities.store') }}">
        @csrf
        <input type="hidden" name="event_id" value="{{$event->id}}">
        <input type="hidden" name="status" value="0">
        <div class="form-group">
          <label for="inputDescription">Descripción</label>
          <input type="text" class="form-control" id="inputDescription" name="description" aria-describedby="descriptionHelp" placeholder="Ingrese la descripción" value="{{ old('description') }}" required>
          <small id="descriptionHelp" class="form-text text-muted">Ingrese la descripción de la actividad a crear</small>
        </div>
        <div class="form-group">
          <label for="inputStartDate">Fecha de inicio</label>
          <input type="datetime-local" class="form-control" id="inputStartDate" name="start_date" aria-describedby="start_dateHelp" placeholder="DD/MM/AAAA" value="{{ old('start_date') }}" required>
          <small id="start_dateHelp" class="form-text text-muted">Ingrese la fecha de inicio de la actividad a crear</small>
        </div>
        <div class="form-group">
          <label for="inputEndDate">Fecha de fin</label>
          <input type="datetime-local" class="form-control" id="inputEndDate" name="end_date" aria-describedby="end_dateHelp" placeholder="DD/MM/AAAA" value="{{ old('end_date') }}" required>
          <small id="end_dateHelp" class="form-text text-muted">Ingrese la fecha de fin de la actividad a crear</small>
        </div>

        <div class="form-group">
          <label for="inputCapacity">Capacidad de la actividad</label>
          <input type="number" class="form-control" id="inputCapacity" name="capacity" aria-describedby="capacityHelp" placeholder="Capacidad" value="{{ old('capacity') }}" required>
          <small id="capacityHelp" class="form-text text-muted">Ingrese la capacidad de la actividad a crear</small>
        </div>

          <div class="form-group">
                    <label for="selectResponsible">Responsable de la actividad</label>
                    <select class="form-control" name="user_id" id="selectResponsible">
                      <option value="" selected>Seleccionar responsable</option>
                      @foreach($users as $user)
                      <option value="{{ $user->id }}">{{ $user->name }}</option>
                      @endforeach
                    </select>
         </div>
        <div class="form-group">
                    <label for="selectType">Tipo de actividad</label>
                    <select class="form-control" name="type" id="selectType">
                      <option value="" selected>Seleccionar tipo</option>
                      <option value="Forum">Foro</option>
                      <option value="Presentation">Ponencia</option>
                      <option value="Conference">Conferencia</option>
                    </select>
         </div>

         <div class="form-group">
                    <label for="selectPlace">Espacio donde se dará</label>
                    <select class="form-control" name="place_id" id="selectPlace">
                      <option value="" selected>Seleccionar espacio</option>
                      @foreach($places as $place)
                      <option value="{{ $place->id }}">{{ $place->description }}</option>
                      @endforeach
                    </select>
         </div>
         <div class="form-group">
                    <label for="selectThematic">Temática de la actividad (opcional)</label>
                    <select class="form-control" name="thematic_id" id="selectThematic">
                      @foreach($thematics as $thematic)
                      <option value="{{ $thematic->id }}">{{ $thematic->description }}</option>
                      @endforeach
                    </select>
         </div>
        <button type="submit" class="btn btn-primary">Crear actividad</button>
      </form>
    </div>
  </div>
</div>


@section('pagescript')
<script src="{{asset('/js/events.js')}}"></script>
@stop

@endsection

resources/views/activities/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <div class="mb-3">
    <h3 class="d-inline">
      Datos de actividad
    </h3>
    @if(Auth::user() && (Auth::user()->roles()->where('name','admin')->first() || $activity->event->organizers->contains(Auth::user()->id)) && $activity->type == 'Presentation')
     <a class="btn btn-info mb-3 float-right mr-2" href="{{ route('referees.search', $activity->id) }}">Añadir árbitros</a>
    @endif
  </div>
  <div class="card mb-3">
    <div class="float-left">
      <h3 class="card-header">{{ $activity->description }}</h3>
      <div class="card-body">
        <h5 class="card-title">Evento : {{ $activity->event->description }}</h5>
        <h5 class="card-title">{{ __($activity->type) }}</h5>
        <h5 class="card-title">Responsable : {{ $activity->responsible->name }}</h5>
        <h6 class="card-subtitle text-muted">Espacio : {{ $activity->place->description }}</h6>
      </div>
    </div>
    <div class="card-body">
      @if($activity->thematic)
      <p class="card-text">Temática: {{ $activity->thematic->description }}</p>

      @endif
      <p class="card-text">Capacidad: {{ $activity->capacity }} </p>
      <p class="card-text">Hora inicio:  {{ Carbon\Carbon::parse($activity->start_date)->format('d/m/Y h:m a') }} </p>
      <p class="card-text">Hora fin: {{ Carbon\Carbon::parse($activity->end_date)->format('d/m/Y h:m a') }} </p>
      <p class="card-text">Árbitros asignados: {{ $activity->referees->count() }} </p>
    </div>
    <div class="card-footer text-muted">
      Texto
    </div>
  </div>

  @if(Auth::user() && (Auth::user()->roles()->where('name','admin')->first() || $activity->event->organizers->contains(Auth::user()->id)) && $activity->type == 'Presentation')
  @if($activity->referees->count() > 0)
<div class="mb-3">
  <h4 class="d-inline">
    Árbitros
  </h4>
</div>
<div class="bs-component">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">E-mail</th>
        <th scope="col">Telefono</th>

      </tr>
    </thead>
    <tbody>
      @foreach($activity->referees as $referee)
      <tr>
       <td>
         {{ $referee->name }}
       </td>
       <td>
        {{ $referee->email }}
      </td>
      <td>
        {{ $referee->phone }}
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
</div>
@endif
@endif


</div>


@section('pagescript')
<script src="{{asset('/js/events.js')}}"></script>
@stop

@endsection